name: Pre-release

on:
  create

jobs:

  # Make a PR to master from a new branch with changes, and delete the created one
  pre-release:

    # Only run when a release-v* branch is created, and not by drashbot
    if: contains(github.ref, 'release-v') && !contains(github.event.sender.login, 'drashbot')

    strategy:
      matrix:
        deno: ["1.5.2"]

    runs-on: ubuntu-latest

    steps:
      - name: Notify the castle that this module needs to be prepped for release
        run: |
          curl -X POST \
            -u "${{ secrets.CI_USER_NAME }}:${{ secrets.CI_USER_PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json"
            --data '{"event_type": "pre_release", "client_payload": { "repo": "deno-drash", "module": "drash", "version": "${{ github.ref }}" }}'
            https://api.github.com/repos/drashland/castle/dispatches
